import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";
import UserProvider from "@/contextApi/UserContextProvider";
import { ToastContainer } from "react-toastify";
import { BannerContext } from "@/contextApi/UserContext";
import BannerContextProvider from "@/contextApi/BannerContextProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <main>
            <BannerContextProvider>
              <UserProvider>
                {children}
                <ToastContainer />
              </UserProvider>
            </BannerContextProvider>
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
